sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
language: java
jdk: oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
install: true
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/855ef506a5ef23e49ab7
    on_success: change
    on_failure: always
    on_start: never
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc
  -out $GPG_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc
  -out $GPG_DIR/secring.gpg -d
- "$GPG_DIR/publish.sh"
env:
  global:
  - GPG_DIR="`pwd`/deploy"
  - secure: fKZJfjUgYCes9JWy9l4R86f1iajFKaPflJXWJ1+qxuGdQjq+R0gohldUUs4utSwmZWFenHgkkDEZ8S2lV/X13GnJ0zCmImA5vb1SGy+HvyxXDVSKUTYrHAejIdBfiTJ+MBDqeXi0ehg8aQErJz+Q/Cb7YjI0WJ5Xf8Pr3Ak4B+VMJ+WJpkTUBV51gw/EnbfslgL5a9jDERIZ64pOjlyv1C3OaJ840tGOvYGrPzbjqyg+5T5e8BKNWlRorn1U+BeOPLlES+b+1Nug0TysmS9ucZTGqWHJfurFyoWfnyLXJ09NFX2n2tKd9I4t/dkLeVLuBt3M6mboohB5ludRxxpmx9T1ubdU68Qa/OZa+Dm719AaTrmAJInItCnY5xONaW1CB/ATVrf49ukicBaNQgaSai/pQx96VZ0mXbFz6yWg1mrDYdlLedEw4pn0yM0eEsyr3ipdCcA4IobSyoeSizZezKfr6OE73g36hswS/Qipzmq/qrm9KBwtULlSVfNzZMkbQjCIyWHet7X5K3hR00GahOdCw/Iv5Ata0a9uJVLZ4RCQeBjke8+R1H2Y96QPOnwEE6NGjmaCKx4GrG6Q4PiujVTf3dxkWdLq8xDk4u+8JSdiTvDa89eDsq5RjWq+YUz+T0dUqfQ3dK9DPsJd7X2vZB7C4+jYQlQj/1g1KyQlFjI=
  - secure: GYKzVU03uxRCHBjBFysOcJgZczQv8Q28Kfs2tHyMO9dveFgOHEiCiF5YEHTprlzOw3WhtMW+i31ON8JRYt1UBsJyAYzpQuRk+orRA3SsnLI2wDTWORmOAUt/ID+MZC7vx3ijH2lO/E59L6DYmf9lWE1SDtSLAEYA8ZU/ZZJrXvRIG0EEhy1Bt1smnazjVyB8ywr2JP6egZokkMSjGxoxge0HOXyKuY8u0tHawKkdRRo5c3oUR/xTvQpEgLgs1ZBBcZYRm0fSL1RBIEFvTQjMiYOB3ttwRSrso3rOFPnbgU/rGpYJKnL7r8V0bUiG7ZHPK3F0OQmwS0ufFMouTd6Nzconqj5RB9sCHJ3vjQdcbNjPyApzxz/IYl8XMq9lvUW4W4iC3OsGlAWJ0F1Crp9lIGsqC9Pg3gO277yK7mvb15o//mOFnRuw/C9F+yOq18I3LWgXxclavvK1Bv0E/H/jMintJO0qwhdQXoD9JmRdMeRJfu4MGt6blSVkArokYGPuvZuYzGrrpEc/Fmji+9tGIqZo4puliBw9OCLog8iM9z3AJ+egtuXrFbKmy6wu6Qi6Ijs/W2lMGRpgxBk5y7AyxqBNlk0bsK9pX4KXElqPP8kP0THE9XyyX1BilF8YslxCZEQnMNEnzgmvzRdH6ZCUHNdcSSuFtrkwr5WfYV8INg4=
  - secure: Y+XpxqxUGHQSxxsK2eMtFsMx6TYEJyxERud7Uf2TND70dTzFRDW23E1WGLiSWadSNYMQkbEKOOyraMWqTzjEYfnk3A1TekV3eoR1CI2FDF++SVmMm3XUX5qXDYYa7aYerPnvM6cr8jV6fX+9APxrWKk5aMI6YJDPmJbFCppswkfHfsfCO127VxPj66VZofel9h0ubKT2W6EJCdCWEGrxRpFZbFGjq2dPbCM0fAdOlzy85YGZG9dw0IlfjJsdj2NWizKEFNm4aoXFe+FqIOIyGNFO7N7VXeCqNUvGkYXxcUKhxiA6pf4qEBo5l3QqHz+DctC3Vpf9w2sb04JwZB9PW5ZV4pV5JD/q+r+pKddPF43ZRvqOdfwnOxt1vMUlincB5Qxrm1GpBqbnqoyK2pX+Il18K/mgRO1EpYb57P3nHyfJKuDKwSRBqqUV36YgyuGQgHGMIvXQHlDXM2OoCI4SgluzzDPTzenv8M+c/fviXb1K5MRMwu1c5mfiE6mB46ZTLWRbik1rvG9U41qLhGS9nU7ZRzZyVTRoXo5VmX/XjvpWNP0sVCNw7axCZCCC5XX3Gc7GhWd1cjZv3n38BT6iSobh+s9N4kVez2oeRvytyVd5LV39fgdXvBXjIaZ2APVsUzH4xEE3iOF3xNnEMJfcgOPc7xCLyFmegMHwYiMq7fQ=
  - secure: WGSaLm5QQum2bHYeRXUeP6l4kTGxFLKG5T0HgKBh1wBCsEVOvwcA8SAAKROrNjFQ1o3J+a/SWOsUL4Gumr+2jItujkxiK934j/5AHKHzpF5Lufs906L7TBHIcLhFjpBt+YENjaPw7BSfTDAkSJAwgOjzuDBhLAuICrvbkbK0krGJcIoo81IPN9bnzGDd1RhcwJoedB4XxnHdELbd5166UaGNAXYas5w9G5lw/caxi94wBl8n4I33vt9n5ldM7Y1UPYtI+55lKK7Qwt60h3AZWOXCZfmaGujfBnq6znrU5zc43Zx3INCMQ2VMzK0rCTaEV5D7Td9K9hcXS0seLOZrR5pYMWnT9dhDs3MoxSV3sGYgE8W6idKSxbJM01kX0NJpVlJsmCcEosPeZ0Q6tIoh4d2Tg5Y8InOFsUhpUTFgy16U5BrKdWtP/F1T6RoFIfsS9e+Iqt6gJ5suO1EInX1pDqVAmOY4SKQQFift+mC4+/nTvCWfgEHRTbF1rKybHMYRltbzT+4tzAF+b0V6e34zxZMexWoMgNFUBBQgc1hUHAcHaBUYu+05n0K4a23kNCqV4Wcj91RNN6NiiUrff2UYsQbjFOmjlUDCewhafe03UMiPqX+2qqBFHp5WbnQw4H7hpOEnhMPPINXvZNqwQ4PeUQP0B8MafwMBPIopC17/xIU=
  - secure: eTxpjSAiZwUfEcb3EMNXV6FVYtMmYp98gHIg2mhXK5zk6csuuYc3AtqePgCn4jT/qjh8huDB6oJwCIrvP2JG4fyztQAngF52Nsug5P9s7OOPOLfslmCEXdKBmt9FcWQTQyXdpHvolGPZ2WHZ3PhzJzQc+S7QobGPZ8bMEm8LF/uSFEn8X1/l8DwxJFZwDJNYv+ey5WxRSlwFS0oerMHuk+sMoy2yPkw/MOZs0itvBdGv6lvZJIWpwH48DjKXEy7nMRtTWIoDw/2jvrq4kkgCmT3WgFy41T/nYi4Hj7q7JFivMGi/9nL8zNupC5KQ2AmPqLs4ldZqcsY2mFrtehBiJ1V8Jtn9u/vjOf250uoSM/Fi6KpFyzV2Y/ThgonhS20gZVJJ5aNa0xrpUcxCUcnwl7WfS1RSUh0O8veV06lcWOyc1UonI0TyQOG5VVD0Y3itc7qyYBpWoeyDtFGFrgI+bdO4QmAomkTF5a5HLqFrBFSQUs6bpXwpfW9bpsU0UwDo83lMR0wbH8kaXw0vLwi+EKW5EhCvtDw28tzFjbfd7+fp2391+YhlecKFFb7rVUHEV8kNFOKVg5SJsjmBBlYJzNtlGVnq5Bb8a3MD2UmBMddMRAgzsF2OMvpusVDbtXQxqR3Ui6zXXrWHG6tUKDGFPaqiO9nV2Cv+ChqIjXM2TeA=
